FROM node:lts-hydrogen

WORKDIR /frontend

ENV SHELL=/bin/sh LANG=en_US.UTF-8

RUN apt-get update && \
  apt-get install -y \
  curl \
  net-tools \
  build-essential

COPY package.json package-lock.json /frontend/

RUN npm ci && \
  npm cache clean --force && \
  npm cache verify

COPY . /frontend/

RUN npm run build
CMD npm run start
