services:
  postgres:
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    restart: on-failure

  django:
    build:
      context: .
      dockerfile: dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver"
    ports:
      - 8000:8000
    environment:
      DJANGO_DB_NAME: postgres
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: postgres
      DJANGO_DB_HOST: postgres
      DJANGO_DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/backend
    restart: on-failure

  vite:
    build:
      context: frontend/
      dockerfile: dockerfile
    command: npm run dev
    ports:
      - 3000:3000
    depends_on:
      django:
        condition: service_started
    volumes:
      - ./frontend:/frontend
    restart: on-failure

  nginx:
    image: nginx:stable
    network_mode: host
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
