# Generated by Django 4.1.6 on 2023-02-06 02:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DRUG", "Drug"),
                            ("SUPPLEMENT", "Supplement"),
                            ("COSMETIC", "Cosmetic"),
                            ("HYGIENE", "Hygiene"),
                            ("BABY_AND_KIDS", "Baby And Kids"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField(max_length=256)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="product.brand")),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="product.product")),
            ],
        ),
    ]
