# Generated by Django 4.1.6 on 2023-03-16 22:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128)),
                (
                    "types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("DRUG", "Drug"),
                                ("SUPPLEMENT", "Supplement"),
                                ("COSMETIC", "Cosmetic"),
                                ("HYGIENE", "Hygiene"),
                                ("BABY_AND_KIDS", "Baby and Kids"),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=32)),
                ("quantity", models.PositiveIntegerField()),
                ("description", models.TextField(max_length=2048)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="brands.brand")),
            ],
            options={
                "ordering": ["updated_at"],
            },
        ),
    ]
