# Generated by Django 4.1.6 on 2023-03-16 23:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("DRUG", "Drug"),
                        ("SUPPLEMENT", "Supplement"),
                        ("COSMETIC", "Cosmetic"),
                        ("HYGIENE", "Hygiene"),
                        ("BABY_AND_KIDS", "Baby and Kids"),
                    ],
                    max_length=32,
                    null=True,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
