# Generated by Django 4.1.6 on 2023-03-17 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-updated_at"]},
        ),
    ]
